package com.example.FlashCards.model;

import java.sql.Time;

public enum Subject {
    FOOD,
    FAMILY,
    BODY_AND_HEALTH,
    TIME_AND_DATE,
    WORK_AND_PROFESSIONS,
    HOUSE_AND_APARTMENT,
    TRAVEL_AND_TOURISM,
    SHOPPING_AND_TRADING,
    SCHOOL_AND_EDUCATION,
    ACTIVITIES_AND_DAILY_ACTIVITIES,
    ENVIRONMENT_AND_NATURE,
    SPORT_AND_RECREATION,
    CULTURE_AND_ART,
    TECHNOLOGY_AND_COMPUTERS,
    SOCIAL_RELATIONS_AND_EMOTIONS,
    OTHER;
}